### ISSUE TITLE
Error when ffi: ^0.1.2

### ISSUE THREAD

**Issue by crazecoder** [dart-lang/samples#16]
```
Error: Expected 0 type arguments.
class Utf8 extends Struct<Utf8> {
                   ^
Error: Expected 0 type arguments.
class Utf16 extends Struct<Utf16> {
                    ^
Error: Type argument 'Utf8' doesn't conform to the bound 'NativeType' of the type variable 'T' on 'Pointer'.
 - 'Utf8' is from 'package:ffi/src/utf8.dart'.
 - 'NativeType' is from 'dart:ffi'.
Try changing type arguments so that they conform to the bounds.
  static int strlen(Pointer<Utf8> string) {
                                  ^
Error: Type argument 'Utf8' doesn't conform to the bound 'NativeType' of the type variable 'T' on 'Pointer'.
 - 'Utf8' is from 'package:ffi/src/utf8.dart'.
 - 'NativeType' is from 'dart:ffi'.
Try changing type arguments so that they conform to the bounds.
  static String fromUtf8(Pointer<Utf8> string) {
                                       ^
Error: Type argument 'Utf8' doesn't conform to the bound 'NativeType' of the type variable 'T' on 'Pointer' in the return type.
 - 'Utf8' is from 'package:ffi/src/utf8.dart' .
 - 'NativeType' is from 'dart:ffi'.
Try changing type arguments so that they conform to the bounds.
  static Pointer<Utf8> toUtf8(String string) {
                             ^
 Error: Type argument 'Utf16' doesn't conform to the bound 'NativeType' of the type variable 'T' on 'Pointer' in the return type.
 - 'Utf16' is from 'package:ffi/src/utf16.dart' .
 - 'NativeType' is from 'dart:ffi'.
Try changing type arguments so that they conform to the bounds.
  static Pointer<Utf16> toUtf16(String s) {
                               ^
Error: Type argument 'Utf8' doesn't conform to the bound 'NativeType' of the type variable 'T' on 'Pointer'.
 - 'Utf8' is from 'package:ffi/src/utf8.dart' .
 - 'NativeType' is from 'dart:ffi'.
Try changing type arguments so that they conform to the bounds.
  final systemP = dylib.lookupFunction<SystemC, SystemDart>('system');
                        ^
Error: Inferred type argument 'Utf8' doesn't conform to the bound 'NativeType' of the type variable 'T' on 'Pointer'.
 - 'Utf8' is from 'package:ffi/src/utf8.dart'.
 - 'NativeType' is from 'dart:ffi'.
Try specifying type arguments explicitly so that they conform to the bounds.
  final systemP = dylib.lookupFunction<SystemC, SystemDart>('system');
        ^
Error: Inferred type argument 'Utf8' doesn't conform to the bound 'NativeType' of the type variable 'T' on 'Pointer'.
 - 'Utf8' is from 'package:ffi/src/utf8.dart' .
 - 'NativeType' is from 'dart:ffi'.
Try specifying type arguments explicitly so that they conform to the bounds.
  final cmdP = Utf8.toUtf8(command);
        ^
Error: Type argument 'Utf8' doesn't conform to the bound 'NativeType' of the type variable 'T' on 'Pointer'.
 - 'Utf8' is from 'package:ffi/src/utf8.dart' .
 - 'NativeType' is from 'dart:ffi'.
Try changing type arguments so that they conform to the bounds.
  final systemP = dylib.lookupFunction<SystemC, SystemDart>('system');
                        ^
Error: Inferred type argument 'Utf8' doesn't conform to the bound 'NativeType' of the type variable 'T' on 'Pointer'.
 - 'Utf8' is from 'package:ffi/src/utf8.dart' .
 - 'NativeType' is from 'dart:ffi'.
Try specifying type arguments explicitly so that they conform to the bounds.
  final systemP = dylib.lookupFunction<SystemC, SystemDart>('system');
        ^
Error: Inferred type argument 'Utf8' doesn't conform to the bound 'NativeType' of the type variable 'T' on 'Pointer'.
 - 'Utf8' is from 'package:ffi/src/utf8.dart' .
 - 'NativeType' is from 'dart:ffi'.
Try specifying type arguments explicitly so that they conform to the bounds.
  final cmdP = Utf8.toUtf8(command);
        ^
Error: Inferred type argument 'Utf16' doesn't conform to the bound 'NativeType' of the type variable 'T' on 'Pointer'.
 - 'Utf16' is from 'package:ffi/src/utf16.dart' .
 - 'NativeType' is from 'dart:ffi'.
Try specifying type arguments explicitly so that they conform to the bounds.
  final operationP = Utf16.toUtf16(operation);
        ^
Error: Inferred type argument 'Utf16' doesn't conform to the bound 'NativeType' of the type variable 'T' on 'Pointer'.
 - 'Utf16' is from 'package:ffi/src/utf16.dart'.
 - 'NativeType' is from 'dart:ffi'.
Try specifying type arguments explicitly so that they conform to the bounds.
  final fileP = Utf16.toUtf16(file);
        ^
Error: The argument type 'Pointer<Utf16>' can't be assigned to the parameter type 'Pointer<NativeType>'.
 - 'Pointer' is from 'dart:ffi'.
 - 'Utf16' is from 'package:ffi/src/utf16.dart' .
 - 'NativeType' is from 'dart:ffi'.
      ffi.nullptr, operationP, fileP, ffi.nullptr, ffi.nullptr, SW_SHOWNORMAL);
                   ^
Error: The argument type 'Pointer<Utf16>' can't be assigned to the parameter type 'Pointer<NativeType>'.
 - 'Pointer' is from 'dart:ffi'.
 - 'Utf16' is from 'package:ffi/src/utf16.dart'.
 - 'NativeType' is from 'dart:ffi'.
      ffi.nullptr, operationP, fileP, ffi.nullptr, ffi.nullptr, SW_SHOWNORMAL);
                               ^
Error: The method 'asExternalTypedData' isn't defined for the class 'Pointer<Uint8>'.
 - 'Pointer' is from 'dart:ffi'.
 - 'Uint8' is from 'dart:ffi'.
Try correcting the name to the name of an existing method, or defining a method named 'asExternalTypedData'.
    final Uint8List nativeString = array.asExternalTypedData(count: _maxSize);
                                         ^^^^^^^^^^^^^^^^^^^
Error: The method 'asExternalTypedData' isn't defined for the class 'Pointer<Uint8>'.
 - 'Pointer' is from 'dart:ffi'.
 - 'Uint8' is from 'dart:ffi'.
Try correcting the name to the name of an existing method, or defining a method named 'asExternalTypedData'.
        string.cast<Uint8>().asExternalTypedData(count: length).buffer,
                             ^^^^^^^^^^^^^^^^^^^
Error: Method not found: 'Pointer.allocate'.
        Pointer<Uint8>.allocate(count: units.length + 1);
                       ^^^^^^^^
Error: The method 'asExternalTypedData' isn't defined for the class 'Pointer<Uint8>'.
 - 'Pointer' is from 'dart:ffi'.
 - 'Uint8' is from 'dart:ffi'.
Try correcting the name to the name of an existing method, or defining a method named 'asExternalTypedData'.
        result.asExternalTypedData(count: units.length + 1);
               ^^^^^^^^^^^^^^^^^^^
Error: The getter 'addressOf' isn't defined for the class 'Utf8'.
 - 'Utf8' is from 'package:ffi/src/utf8.dart' .
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
  String toString() => fromUtf8(addressOf);
                                ^^^^^^^^^
Error: Method not found: 'Pointer.allocate'.
        Pointer<Uint16>.allocate(count: units.length + 1);
                        ^^^^^^^^
Error: The method 'asExternalTypedData' isn't defined for the class 'Pointer<Uint16>'.
 - 'Pointer' is from 'dart:ffi'.
 - 'Uint16' is from 'dart:ffi'.
Try correcting the name to the name of an existing method, or defining a method named 'asExternalTypedData'.
        result.asExternalTypedData(count: units.length + 1);
               ^^^^^^^^^^^^^^^^^^^
Exception: Errors during snapshot creation: null
#0      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/dart.dart:230:7)
<asynchronous suspension>
#1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:526:25)
<asynchronous suspension>
#2      _BuildInstance.invokeTarget.<anonymous closure> (package:flutter_tools/src/build_system/build_system.dart:481:35)
#3      new Future.sync (dart:async/future.dart:222:31)
#4      AsyncMemoizer.runOnce (package:async/src/async_memoizer.dart:43:45)
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:481:21)
<asynchronous suspension>
<asynchronous suspension>
#6      BuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:419:36)
#7      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#8      BuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:400:28)
#9      buildWithAssemble (package:flutter_tools/src/bundle.dart:125:48)
#10     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#11     buildWithAssemble (package:flutter_tools/src/bundle.dart:99:31)
#12     BundleBuilder.build (package:flutter_tools/src/bundle.dart:75:11)
#13     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#14     BundleBuilder.build (package:flutter_tools/src/bundle.dart:52:21)
#15     BuildBundleCommand.runCommand (package:flutter_tools/src/commands/build_bundle.dart:126:25)
#16     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#17     BuildBundleCommand.runCommand (package:flutter_tools/src/commands/build_bundle.dart:97:42)
#18     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:557:18)
#19     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#20     _rootRunUnary (dart:async/zone.dart:1132:38)
#21     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#22     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#24     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#25     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#26     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#27     _rootRun (dart:async/zone.dart:1124:13)
#28     _CustomZone.run (dart:async/zone.dart:1021:19)
#29     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#30     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#31     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#32     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#33     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```
flutter doctor
```
[✓] Flutter (Channel master, v1.10.15-pre.307, on Mac OS X 10.15.1 19B88)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Xcode - develop for iOS and macOS (Xcode 11.1)
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods. For more info, see https://github.com/flutter/flutter/issues/14293.
      To re-install CocoaPods, run:
        sudo gem install cocoapods
[✓] Chrome - develop for the web
[!] Android Studio (version 3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Community Edition (version 2019.2.3)
[✓] VS Code (version 1.39.2)
[✓] Connected device (3 available)

! Doctor found issues in 2 categories.
```

**Comment by dcharkes** [comment]
The `dart:ffi` [API changes](https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md#foreign-function-interface-dartffi) for Dart 2.6 have rolled into flutter.

We need to update these samples. Note that updating the samples will make them incompatible with Dart 2.5.

@johnpryan @mkustermann

**Comment by dcharkes** [comment]
I would much rather have these samples _in_ the sdk, in https://github.com/dart-lang/sdk/tree/master/samples/ffi. That way I can update them easily in lock-step with API changes.

@kwalrath Is there a specific reason that these samples are in a separate repository?

**Comment by kwalrath** [comment]
> I would much rather have these samples _in_ the sdk, in https://github.com/dart-lang/sdk/tree/master/samples/ffi. That way I can update them easily in lock-step with API changes.
> 
> @kwalrath Is there a specific reason that these samples are in a separate repository?

@mjohnsullivan should be able to answer that question.

**Comment by mjohnsullivan** [comment]
@RedBrogdon & @johnpryan for discussion on what's in our samples projects.

**Comment by johnpryan** [comment]
@dcharkes We would like to use the same approach as https://github.com/flutter/samples, where the samples are compatible with the latest stable SDK. Once Travis CI is set up we can run additional jobs against the dev SDK or master.

**Comment by johnpryan** [comment]
That sounds good to me. Our intention is to manage the maintenance for these samples, but it doesn't hurt to test them in the SDK too.  Let me know if you would like help setting that up.

**Comment by dcharkes** [comment]
> Our intention is to manage the maintenance for these samples, but it doesn't hurt to test them in the SDK too. Let me know if you would like help setting that up.

If we pull the samples into the SDK, then we have to maintain them on SDK commits, as we cannot land SDK commits anymore that break the samples. This would put the burden of maintenance on SDK committers.

Concretely for this issue, are you going to fix the samples after D26, or should I do it?

**Comment by johnpryan** [comment]
The FFI samples are now up to date (#19)

**Comment by jinfagang** [comment]
How to solve errors???

![image](https://user-images.githubusercontent.com/21303438/135747379-4eb96ab2-9ea3-4f21-bbd0-9bbfdd2c03e2.png)

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 2.6.0-12.0.pre.185, on Ubuntu 20.04 LTS 5.4.0-81-generic, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.45.1)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.

```

**Comment by dcharkes** [comment]
@jinfagang please open a new issue with a reproduction steps.

**Comment by Jaquelinebertoldo** [comment]
I'm having the same problems, I've tried to update the dependencies of the packages that the project uses, but without success
