### ISSUE TITLE
loading shared libs on linux

### ISSUE THREAD

**Issue by yvs2014** [dart-lang/samples#185]
Hello, can you please give a hint how to properly load shared libs on linux?

For example, trying to load 'libncursesw.so' on linux ubuntu with `DynamicLibrary.open("libncursesw.so");` got
```
Invalid argument(s): Failed to load dynamic library 'libncursesw.so': /lib/x86_64-linux-gnu/libncursesw.so: file too short
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
```

Inspecting it a bit:
`pkg-config -libs ncursesw` says `-lncursesw -ltinfo` and content of `/lib/x86_64-linux-gnu/libncursesw.so` is `INPUT(libncursesw.so.6 -ltinfo)`, given that I can load ncursesw lib with `DynamicLibrary.open("libncursesw.so.6");` and in this case there's no errors and it looks like it works, but totally not sure if that can be applied to all kinds of linux

**Comment by yvs2014** [comment]
I didn't spot this line in documentation
"The path must refer to a native library file which can be successfully loaded."
https://api.dart.dev/dev/3.3.0-120.0.dev/dart-ffi/DynamicLibrary/DynamicLibrary.open.html

Sorry for disturbig, this question is closed
