### ISSUE TITLE
struct sample broken after upgrading dart through dev channel

### ISSUE THREAD

**Issue by kakyoism** [dart-lang/samples#45]
I was on Dart 2.6.1 on macOS Catalina and just upgraded through homebrew and flutter dev channel

Here is my `flutter doctor -v`

```sh
$ flutter doctor -v
[✓] Flutter (Channel dev, v1.16.4-pre.50, on Mac OS X 10.15.4 19E266, locale en-CN)
    • Flutter version 1.16.4-pre.50 at /Applications/flutter
    • Framework revision d14a301e41 (29 hours ago), 2020-03-31 19:14:22 -0400
    • Engine revision fc5b44c901
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 e8c4aed700)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Applications/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Applications/Android/sdk
    • ANDROID_SDK_ROOT = /Applications/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains localhost

[✓] Connected device (1 available)
    • MyiPhone • b06f169665fe7a20d2dfcc6ae06b02247e557d06 • ios • iOS 13.4


```

## Repro

```sh
$ brew install dart --devel
...
$ brew upgrade dart-lang/dart/dart
...
$ dart --version
Dart VM version: 2.7.2 (Mon Mar 23 22:11:27 2020 +0100) on "macos_x64"
```

Then running `dart structs.dart` as usual throws the dylib load exception at me 

```shell
$ dart structs.dart 
Unhandled exception:
Invalid argument(s): Failed to load dynamic library (dlopen(./structs_library/libstructs.dylib, 1): no suitable image found.  Did find:
	file system relative paths not allowed in hardened programs)
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:13:55)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
#2      main (file:///Users/kakyo/Desktop/_task/MMT/research/hello-mamguest/hello_dart/structs/structs.dart:84:36)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

This sample used to work perfectly right before I upgraded Dart.
How should I fix this?

**Comment by kakyoism** [comment]
Found the solution myself.

```sh
codesign --remove-signature `which dart`
```

**Comment by dcharkes** [comment]
From Dart 2.8.0 v9 it should have the right entitlements to load unsigned libraries. See discussion on https://github.com/dart-lang/sdk/issues/38314#issuecomment-584625936.
